import scrapy 
import re
#need to figure out exactly how the items file helps, should it be used for this?
#the next big step is going to be going to the individual episode's page and scraping the description
class EpisodeInformation(scrapy.Spider):
	name = 'episodes'
	allowed_domains =['frasieronline.co.uk']
	start_urls = [
		'http://www.frasieronline.co.uk/episodeguide/'
	]
	
	def parse(self, response):
		
		seasons = response.xpath("//tr//p[1]/a/@href").extract()	
		
		for season in seasons:
			episodePage = response.urljoin(season)
			yield scrapy.Request(episodePage, callback=self.parse_season)
			
	def parse_season(self, response):
		
		#removes all the gross whitespace. attempts to remove the '\\n' but fails, i think it is generated by scrapy and not xpath
		def clean_up(query):
			dirty_text = str(response.xpath(query).extract())
			cleaner_text = (re.sub('\s\s+',' ', dirty_text))
			clean_text = (re.sub('\\n','', cleaner_text))
			return clean_text
			
		#gets the number for the season label
		def ep_number(title):
			title_string = str(response.xpath(title).extract())
			return re.sub('\D','',title_string)
			
			
		
		yield {

			
			('Episodes for Season: ' + ep_number('head/title/text()')) : clean_up("//td[@class='epguide_Title']/a/text()"),
			

		}
		
		


			
		

